/**
 * NYSE trading calendar, read from the generated session list.
 *
 * Spec A6. Every freshness threshold in the health check used to be wall-clock:
 * chain capture runs Mon–Fri, the check failed at >48h, so the check went red
 * every Saturday night and stayed red until Monday. Run 31984884170 posted a 🚨
 * Discord embed at 01:25 Sunday with nothing wrong. Two of those and the channel
 * stops being read — which also destroys the premise of the daily proof-of-life
 * push, whose whole value is that its absence is noticeable.
 *
 * "One trading day" is the only threshold that means the same thing on a Tuesday
 * and over Thanksgiving weekend.
 *
 * The holiday list is not maintained here. web/src/lib/nyse-sessions.json is
 * generated by scripts/generate_nyse_calendar.py from the `exchange_calendars`
 * library, and CI fails if the committed copy drifts.
 */

import calendarData from './nyse-sessions.json'

const SESSIONS: string[] = calendarData.sessions
const SESSION_SET = new Set(SESSIONS)
const EARLY_CLOSES: Record<string, string> = calendarData.early_closes
const RANGE = calendarData.range

/** YYYY-MM-DD for an instant, in US Eastern — the exchange's own day. */
export function etDate(at: Date = new Date()): string {
  // en-CA gives ISO-ordered parts, so this is a date string, not a locale render.
  return at.toLocaleDateString('en-CA', { timeZone: 'America/New_York' })
}

/** Minutes since ET midnight. */
export function etMinutes(at: Date = new Date()): number {
  const hhmm = at.toLocaleTimeString('en-GB', {
    timeZone: 'America/New_York', hour: '2-digit', minute: '2-digit', hour12: false,
  })
  const [h, m] = hhmm.split(':').map(Number)
  return h * 60 + m
}

export class CalendarRangeError extends Error {}

/**
 * The generated file covers a fixed range. Past the end, every answer would be
 * silently wrong — "no sessions since X" reads exactly like a dead pipeline. So
 * running off the end throws, and the health check reports it as a failure
 * rather than inventing a verdict.
 */
function assertInRange(day: string) {
  if (day < RANGE.start || day > RANGE.end) {
    throw new CalendarRangeError(
      `${day} is outside the generated NYSE calendar (${RANGE.start}..${RANGE.end}). ` +
        'Run scripts/generate_nyse_calendar.py to extend it.',
    )
  }
}

export function isTradingDay(day: string): boolean {
  assertInRange(day)
  return SESSION_SET.has(day)
}

/** Close time in ET for a session, accounting for 1 PM half days. */
export function closeMinutesET(day: string): number {
  const early = EARLY_CLOSES[day]
  if (early) {
    const [h, m] = early.split(':').map(Number)
    return h * 60 + m
  }
  return 16 * 60
}

const OPEN_MINUTES = 9 * 60 + 30

/** True during the RTH session, half days included. */
export function isMarketOpen(at: Date = new Date()): boolean {
  const day = etDate(at)
  if (!isTradingDay(day)) return false
  const mins = etMinutes(at)
  return mins >= OPEN_MINUTES && mins < closeMinutesET(day)
}

/**
 * Sessions that have CLOSED between two instants — the correct unit for "how
 * stale is this data". A capture from Friday afternoon is zero closed sessions
 * old at any point over the weekend, and one closed session old after Monday's
 * bell. That is the whole fix for the weekend false alarm.
 */
export function tradingDaysSince(since: Date, now: Date = new Date()): number {
  const from = etDate(since)
  const to = etDate(now)
  assertInRange(from)
  assertInRange(to)
  if (from > to) return 0

  let n = 0
  for (const s of SESSIONS) {
    if (s <= from) continue
    if (s > to) break
    n += 1
  }
  // Today's session only counts once it has actually closed; otherwise data
  // captured after yesterday's bell looks a day stale all through this morning.
  if (SESSION_SET.has(to) && to > from && etMinutes(now) < closeMinutesET(to)) {
    n -= 1
  }
  return Math.max(0, n)
}

export const calendarRange = RANGE
