#!/usr/bin/env python3
"""
Generate the NYSE session calendar both readers share.

Spec A6 says: use a real market-calendar library, do not hand-roll holidays. But
the freshness checks that need the calendar live in a Next.js route (TypeScript)
and in Python, and there is no single library both can call. So the real library
runs here, once, and emits a data file that both sides read. Nobody hand-writes a
holiday; `exchange_calendars` does, and CI re-runs this and fails if the output
drifts from what is committed.

Why this matters: every freshness threshold in the health check was wall-clock.
Chain capture runs Mon–Fri, the check failed at >48h, so every Saturday night it
went red and stayed red until Monday — run 31984884170 fired a 🚨 Discord embed
at 01:25 Sunday with nothing wrong. Two red weekends and the channel is noise,
which also destroys the premise of the daily proof-of-life push.

Usage:  python3 scripts/generate_nyse_calendar.py [--check]
        --check exits non-zero if the committed file is stale (for CI).
"""

import argparse
import json
import os
import sys

OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "web", "src", "lib", "nyse-sessions.json",
)

START = "2024-01-01"
END = "2031-12-31"


def build():
    try:
        import exchange_calendars as ec
    except ImportError:
        sys.exit(
            "exchange_calendars is not installed.\n"
            "  pip install exchange_calendars\n"
            "This script deliberately depends on a real calendar library — the "
            "whole point is that nobody hand-maintains a holiday list."
        )

    # get_calendar() defaults to roughly one year ahead. The bounds are passed
    # explicitly so the file covers positions opened today that expire in a
    # LEAPS-length window, and so it does not silently run out mid-year.
    cal = ec.get_calendar("XNYS", start=START, end=END)
    # cal.sessions rather than sessions_in_range(START, END): the calendar
    # snaps its bounds to real sessions, so START/END are not themselves valid
    # arguments once they fall on a weekend or holiday.
    sessions = [str(d)[:10] for d in cal.sessions]

    # Half days (1:00 PM ET close): the day after Thanksgiving, Christmas Eve,
    # July 3rd and friends. Recorded so "is the market open right now" is right
    # on those days too.
    # Derived by comparing each session's actual close to the regular 16:00 ET
    # close, rather than by reading a named "early_closes" attribute whose shape
    # varies across library versions. If the library's opinion changes, --check
    # in CI notices.
    closes_et = cal.closes.dt.tz_convert("America/New_York")
    early = {
        str(day)[:10]: ts.strftime("%H:%M")
        for day, ts in closes_et.items()
        if ts.strftime("%H:%M") != "16:00"
    }

    return {
        "_comment": (
            "GENERATED by scripts/generate_nyse_calendar.py from the "
            "exchange_calendars library. Do not edit by hand — CI regenerates "
            "this and fails on drift. Regenerate before the range runs out."
        ),
        "exchange": "XNYS",
        "generator": "exchange_calendars",
        "generator_version": ec.__version__,
        "range": {"start": START, "end": END},
        "regular_close_et": "16:00",
        "open_et": "09:30",
        "early_closes": early,
        "sessions": sessions,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="fail if the committed file differs from freshly generated")
    args = ap.parse_args()

    data = build()
    text = json.dumps(data, indent=2) + "\n"

    if args.check:
        if not os.path.exists(OUT):
            sys.exit(f"{OUT} does not exist — run this script without --check")
        current = open(OUT).read()
        if current != text:
            sys.exit(
                f"{OUT} is stale.\n"
                "The committed NYSE calendar no longer matches the library — either "
                "exchange_calendars changed a holiday or the range needs extending.\n"
                "Run: python3 scripts/generate_nyse_calendar.py"
            )
        print(f"NYSE calendar is current ({len(data['sessions'])} sessions, "
              f"{data['range']['start']}..{data['range']['end']})")
        return

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(text)
    print(f"Wrote {OUT}: {len(data['sessions'])} sessions "
          f"{data['range']['start']}..{data['range']['end']}, "
          f"{len(data['early_closes'])} early closes "
          f"(exchange_calendars {data['generator_version']})")


if __name__ == "__main__":
    main()
